SELECT T1.AUDITORIUM_NAME, T2.AUDITORIUM_TYPENAME
	FROM AUDITORIUM as T1 INNER JOIN AUDITORIUM_TYPE AS T2
	ON T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE


SELECT T1.AUDITORIUM_NAME, T2.AUDITORIUM_TYPENAME
	FROM AUDITORIUM as T1 INNER JOIN AUDITORIUM_TYPE AS T2
	ON T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE
	WHERE T2.AUDITORIUM_TYPENAME LIKE '%компьютер%'

SELECT st.NAME as [Имя Студента], fc.FACULTY_NAME AS Факультет, pl.PULPIT_NAME AS Кафедра, prof.PROFESSION_NAME AS Специальность, sb.SUBJECT_NAME AS Дисциплина,
	CASE
	WHEN (pr.NOTE = 6) THEN 'шесть'
	WHEN (pr.NOTE = 7) THEN 'семь'
	WHEN (pr.NOTE = 8) THEN 'восемь'
	END [Оценка]
	FROM PROGRESS AS pr INNER JOIN STUDENT AS st
	ON pr.IDSTUDENT = st.IDSTUDENT
	INNER JOIN GROUPS AS gr ON st.IDGROUP = gr.IDGROUP
	INNER JOIN FACULTY AS fc ON gr.FACULTY = fc.FACULTY
	INNER JOIN PROFESSION AS prof ON gr.PROFESSION = prof.PROFESSION
	INNER JOIN SUBJECT AS sb ON pr.SUBJECT = sb.SUBJECT
	INNER JOIN PULPIT AS pl ON sb.PULPIT = pl.PULPIT
	WHERE pr.NOTE BETWEEN 6 AND 8
	ORDER BY pr.NOTE

SELECT pl.PULPIT_NAME AS Кафера, ISNULL(tch.TEACHER_NAME, '***') [Преподаватель]
	FROM PULPIT AS pl LEFT OUTER JOIN TEACHER AS tch
	ON pl.PULPIT = tch.PULPIT


SELECT T1.AUDITORIUM_NAME, T2.AUDITORIUM_TYPENAME
	FROM AUDITORIUM as T1 INNER JOIN AUDITORIUM_TYPE AS T2
	ON T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE

SELECT T1.AUDITORIUM_NAME, T2.AUDITORIUM_TYPENAME
	FROM AUDITORIUM as T1 CROSS JOIN AUDITORIUM_TYPE AS T2
	WHERE T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE

SELECT *
	FROM AUDITORIUM as T1 FULL OUTER JOIN AUDITORIUM_TYPE AS T2
	ON T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE


create table EX1
(    ID  int constraint Idex1_PK  primary key,  
      VAL  varchar(30)       
)

create table EX2
(    ID  int constraint Idex2_PK  primary key,  
      VAL  varchar(30)       
)

INSERT INTO EX1 (ID, VAL)
	VALUES (1, 'value1'),
	(2, 'value2');

INSERT INTO EX2 (ID, VAL)
	VALUES (1, 'value2'),
	(2, 'value3');


SELECT * FROM EX1 FULL OUTER JOIN EX2 ON EX1.VAL = EX2.VAL WHERE EX1.VAL IS NULL
SELECT * FROM EX1 FULL OUTER JOIN EX2 ON EX1.VAL = EX2.VAL WHERE EX2.VAL IS NULL
SELECT * FROM EX1 FULL OUTER JOIN EX2 ON EX1.VAL = EX2.VAL WHERE EX2.VAL IS NULL OR EX1.VAL IS NULL
SELECT * FROM EX1 FULL OUTER JOIN EX2 ON EX1.VAL = EX2.VAL