SELECT pl.PULPIT, pl.FACULTY
	FROM PULPIT pl, FACULTY fc
	WHERE pl.FACULTY = fc.FACULTY
	AND fc.FACULTY in(SELECT pr.FACULTY FROM PROFESSION pr
									WHERE pr.PROFESSION_NAME LIKE '%технология%'
									OR pr.PROFESSION_NAME LIKE '%технологии%');

SELECT pl.PULPIT, pl.FACULTY
	FROM PULPIT pl INNER JOIN FACULTY fc
	on pl.FACULTY = fc.FACULTY
	WHERE fc.FACULTY in(SELECT pr.FACULTY FROM PROFESSION pr
								    WHERE pr.PROFESSION_NAME LIKE '%технология%'
									OR pr.PROFESSION_NAME LIKE '%технологии%');


SELECT DISTINCT PULPIT.PULPIT, FACULTY.FACULTY
FROM FACULTY
INNER JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY 
INNER JOIN PROFESSION ON PROFESSION.FACULTY = FACULTY.FACULTY
WHERE (PROFESSION_NAME LIKE '%технологии%' 
OR PROFESSION_NAME LIKE '%технология%')



SELECT a.AUDITORIUM_NAME, a.AUDITORIUM_TYPE, a.AUDITORIUM_CAPACITY
	FROM AUDITORIUM a
		WHERE AUDITORIUM_NAME = (
			SELECT TOP(1) AUDITORIUM_NAME FROM AUDITORIUM aa
			WHERE aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
			ORDER BY AUDITORIUM_CAPACITY DESC
			);

SELECT fc.FACULTY_NAME, fc.FACULTY
	FROM FACULTY fc
	 WHERE NOT EXISTS (SELECT PULPIT.PULPIT FROM PULPIT);


SELECT TOP 1
	(SELECT AVG(NOTE) FROM PROGRESS 
		WHERE SUBJECT LIKE 'ОАиП')[ОАиП],
		(SELECT AVG(NOTE) FROM PROGRESS 
		WHERE SUBJECT LIKE 'КГ')[КГ],
		(SELECT AVG(NOTE) FROM PROGRESS 
		WHERE SUBJECT LIKE 'СУБД')[СУБД]
	FROM PROGRESS

SELECT pr.IDSTUDENT, pr.NOTE, pr.SUBJECT
	FROM PROGRESS pr
	WHERE pr.NOTE > ALL(SELECT PROGRESS.NOTE FROM PROGRESS
							WHERE SUBJECT LIKE 'ОАиП');

SELECT pr.IDSTUDENT, pr.NOTE, pr.SUBJECT
	FROM PROGRESS pr
	WHERE pr.NOTE > ANY(SELECT PROGRESS.NOTE FROM PROGRESS
							WHERE SUBJECT LIKE 'СУБД');