SELECT t.AUDITORIUM_TYPE,
		MAX(a.AUDITORIUM_CAPACITY)[Максимальная вместимость],
		MIN(a.AUDITORIUM_CAPACITY)[Минимальная вместимость],
		AVG(a.AUDITORIUM_CAPACITY)[Средняя вместимость],
		SUM(a.AUDITORIUM_CAPACITY)[Сумма],
		COUNT(*)[Количество аудиторий]
	FROM AUDITORIUM_TYPE t INNER JOIN AUDITORIUM a
	ON t.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
	GROUP BY t.AUDITORIUM_TYPE


SELECT * 
	FROM(SELECT CASE
		WHEN (p.NOTE in (4, 5)) THEN '4-5'
		WHEN (p.NOTE in (6, 7)) THEN '6-7'
		WHEN (p.NOTE in (8, 9)) THEN '8-9'
		WHEN (p.NOTE = 10) THEN '10'
		END [Note],
		COUNT(*)[Amount]
	FROM PROGRESS AS p
	GROUP BY CASE
		WHEN (p.NOTE in (4, 5)) THEN '4-5'
		WHEN (p.NOTE in (6, 7)) THEN '6-7'
		WHEN (p.NOTE in (8, 9)) THEN '8-9'
		WHEN (p.NOTE = 10) THEN '10'
		END
	) AS a
	ORDER BY CASE a.Note
	WHEN '4-5' THEN 1
	WHEN '6-7' THEN 2
	WHEN '8-9' THEN 3
	WHEN '10' THEN 4
	END


SELECT (2014 - GROUPS.YEAR_FIRST)[COURSE], GROUPS.PROFESSION, FACULTY.FACULTY_NAME, 
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))), 2)[AVG_NOTE]
	FROM FACULTY INNER JOIN GROUPS
	ON FACULTY.FACULTY = GROUPS.FACULTY
		INNER JOIN STUDENT
	ON STUDENT.IDGROUP = GROUPS.IDGROUP
		INNER JOIN PROGRESS
	ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	GROUP BY GROUPS.YEAR_FIRST, GROUPS.PROFESSION, FACULTY.FACULTY_NAME;


SELECT a.FACULTY,
       G.PROFESSION,
	   G.IDGROUP,
	   P.SUBJECT,
       ROUND(AVG(CAST(NOTE AS FLOAT(4))), 2)  Average
	FROM FACULTY a
		INNER JOIN GROUPS G ON a.FACULTY = G.FACULTY
		INNER JOIN STUDENT S ON G.IDGROUP = S.IDGROUP
		INNER JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
	WHERE P.SUBJECT LIKE 'СУБД' OR P.SUBJECT LIKE 'ОАиП'
	GROUP BY a.FACULTY, G.PROFESSION, G.YEAR_FIRST, P.SUBJECT, G.IDGROUP
	ORDER BY Average DESC


SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS Avr
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'ТОВ'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY


SELECT p.SUBJECT, COUNT(p.NOTE) [Amount 8, 9]
	FROM PROGRESS p
	GROUP BY p.SUBJECT, p.NOTE
	HAVING p.NOTE in (8, 9)