SELECT 
	--COALESCE (PROFESSION, 'All professions') AS Profession,
	--COALESCE (SUBJECT, 'All subjects') AS Subject,
	--COALESCE (FACULTY.FACULTY, 'All faculties') AS Faculty,
	GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'идип'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY WITH ROLLUP

SELECT 
	COALESCE (PROFESSION, 'All professions') AS Profession,
	COALESCE (SUBJECT, 'All subjects') AS Subject,
	COALESCE (FACULTY.FACULTY, 'All faculties') AS Faculty,
	GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'идип'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY WITH CUBE


SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'идип'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
UNION
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'хтит'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'идип'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
UNION ALL
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'хтит'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY


SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'идип'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
INTERSECT
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'хтит'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'идип'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
EXCEPT
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS AVR, COUNT(*) as AMOUNT
	FROM GROUPS
		INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY like 'хтит'
	GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY