//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addr
    {
        public long Id { get; set; }
        public Nullable<long> StudentId { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Home { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
